require_relative 'train_timetable/trains_on_marunouchi_branch_line.rb'
require_relative 'train_timetable/trains_operated_only_on_marunouchi_branch_line.rb'
require_relative 'train_timetable/through_operation.rb'
require_relative 'train_timetable/trains_from_or_to_nakano_sakaue_on_marunouchi_main_line.rb'